# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

author: Tuhin Harit
baseurl: ""
url: "https://tuhinharit.github.io"

# Add your google-analytics ID here to activate google analytics
# google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

title: तुहीन हरित
description: एक लेखक तथा वित्तीय अध्ययन में शोधकर्ता
github_username: tuhinharit
# Email and twitter are optional:
email: tuhinharit@gmail.com 
twitter_username: tunedheart

# Set this to true to get LaTeX math equation support
use_math: true

# Everything below here can be ignored, unless you want to change the theme entirely
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  # - jekyll-paginate
  # - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll sit

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge

# Build settings
# paginate:           5
# paginate_path: "/posts/page:num/"